// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpltmfegqjryemandbum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwbHRtZmVncWpyeWVtYW5kYnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Njk0NjgsImV4cCI6MjA2ODI0NTQ2OH0.-NdgjoICyTzo00M4ElORiLuzTYGMBmvjEq73SfpjlUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});